name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents:
        write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Parametrage Signature
      run: echo ${{secrets.JKS}} | base64 --decode > ${{env.CHEMIN_JKS}}${{secrets.NOM_JKS}}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Informations de signature
      env:
        CHEMIN_JKS: ${{env.CHEMIN_JKS}}${{secrets.NOM_JKS}}
      run: | 
        echo storeFile=${CHEMIN_JKS} > ./keystore.properties 
        echo storePassword=${{secrets.TROGNON}} >> ./keystore.properties
        echo keyAlias=${{secrets.POMME}} >> ./keystore.properties
        echo keyPassword=${{secrets.TROGNON}} >> ./keystore.properties

    - name: Compilation et publication
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gradle assembleRelease
        cd ./app/build/outputs/apk/release/
        mv app-release*.apk calculalim.apk
        gh release create ${{github.event.head_commit.message}} calculalim.apk \
          --title "${{github.event.head_commit.message}}" \
          --notes "${{github.event.head_commit.message}}"
  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Parametrage Signature
      run: echo ${{secrets.JKS}} | base64 --decode > ${{env.CHEMIN_JKS}}${{secrets.NOM_JKS}}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Informations de signature
      env:
        CHEMIN_JKS: ${{env.CHEMIN_JKS}}${{secrets.NOM_JKS}}
      run: | 
        echo storeFile=${CHEMIN_JKS} > ./keystore.properties 
        echo storePassword=${{secrets.TROGNON}} >> ./keystore.properties
        echo keyAlias=${{secrets.POMME}} >> ./keystore.properties
        echo keyPassword=${{secrets.TROGNON}} >> ./keystore.properties
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
